#!/usr/bin/env bash
if [[ "$OSTYPE" == "darwin"* ]]; then
    for arg do
      shift
      case $arg in
        (-disable-infer-rw) : ;;
           (*) set -- "$@" "$arg" ;;
      esac
    done

    firtool_darwin --disable-annotation-unknown "$@"
else
    firtool_ubuntu2004 --disable-annotation-unknown "$@"
fi