#!/usr/bin/env bash

ARGS='--add-vivado-ram-address-conflict-synthesis-bug-workaround --dedup --preserve-aggregate=1d-vec --disable-annotation-unknown'

# Workaround
for arg do
  shift
  case $arg in
    (-disable-infer-rw) : ;;
        (*) set -- --add-vivado-ram-address-conflict-synthesis-bug-workaround --dedup --preserve-aggregate=1d-vec --disable-annotation-unknown "$@" "$arg" ;;
  esac
done

if [[ "$OSTYPE" == "darwin"* ]]; then
    firtool_darwin --disable-annotation-unknown --add-vivado-ram-address-conflict-synthesis-bug-workaround --dedup --preserve-aggregate=1d-vec "$@"
else
    firtool_ubuntu2004 --disable-annotation-unknown --add-vivado-ram-address-conflict-synthesis-bug-workaround --dedup --preserve-aggregate=1d-vec "$@"
fi
