name: Self-hosted Difftest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  difftest:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Clone Chiplab Repo
        uses: actions/checkout@v3
        with:
          repository: Invalid-Syntax-NSCSCC/min-chiplab
          lfs: true
          token: ${{ secrets.DIFFTEST_ACCESS_TOKEN }}
          path: chiplab
      
      - name: Prepare Environment
        run: |
          echo "`pwd`/chiplab/toolchains/loongarch32r-linux-gnusf-2022-05-20/bin" >> $GITHUB_PATH
        
      - name: Use Cache
        uses: coursier/cache-action@v6

      - name: Elaborate CPU
        run: make
        
      - name: Move to Chiplab
        run: |
          export CHIPLAB_HOME=`pwd`/chiplab
          make chiplab

      - name: Test
        run: |
          export CHIPLAB_HOME=`pwd`/chiplab
          cd ./chiplab/sims/verilator/run_prog
          ./configure.sh --run func/func_lab9 --threads `nproc` --tail-waveform --tail-simu-trace --waveform-tail-size 200 --trace-tail-size 200
          make -j`nproc` > make_log.txt 2>&1
          sed -i '/RUN simulation/,$!d' make_log.txt
          cat make_log.txt
        
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: difftest-log
          path: |
            ./chiplab/sims/verilator/run_prog/make_log.txt
            ./chiplab/sims/verilator/run_prog/log/**/simu_trace.*
            ./chiplab/sims/verilator/run_prog/obj/**/obj/test.s
